# Dependabot configuration for automatic dependency updates and security scanning
version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Australia/Sydney"
    open-pull-requests-limit: 10
    # Group updates to reduce PR noise
    groups:
      # Group all non-major npm updates together
      npm-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Security updates should be prioritized
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    reviewers:
      - "sergei.davidov@clearroute.io"

  # Enable security updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Australia/Sydney"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"