name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  claude-review:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Setup Claude Code
        uses: anthropics/claude-code-action@beta
        id: claude-code
        # The action will use the GitHub App by default
        # No github_token needed if using the GitHub App
      
      - name: Run Claude Code Review
        run: |
          echo "Claude Code Review completed"
          echo "Review ID: ${{ steps.claude-code.outputs.review-id }}"
      
      # Cleanup on failure
      - name: Cleanup
        if: failure() && steps.claude-code.outputs.token != ''
        run: |
          curl -L \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ steps.claude-code.outputs.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            ${GITHUB_API_URL:-https://api.github.com}/installation/token